// file was generated by kissmath.py at <TODO: add github link>
#pragma once

////// Forward declarations

#include <cmath>
#include <cstdint>

namespace kissmath {
	
	// Use std math functions for these
	using std::abs;
	using std::floor;
	using std::ceil;
	using std::pow;
	using std::round;
	
	// wrap x into range [0,range)
	// negative x wrap back to +range unlike c++ % operator
	// negative range supported
	inline int wrap (int x, int range);
	
	// wrap x into [a,b) range
	inline int wrap (int x, int a, int b);
	
	// returns the greater value of a and b
	inline constexpr int min (int l, int r);
	
	// returns the smaller value of a and b
	inline constexpr int max (int l, int r);
	
	// equivalent to ternary c ? l : r
	// for conformity with vectors
	inline constexpr int select (bool c, int l, int r);
	
	// clamp x into range [a, b]
	// equivalent to min(max(x,a), b)
	inline constexpr int clamp (int x, int a, int b);
	
	// clamp x into range [0, 1]
	// also known as saturate in hlsl
	inline constexpr int clamp (int x);
	
	
	// length(scalar) = abs(scalar)
	// for conformity with vectors
	inline int length (int x);
	
	// length_sqr(scalar) = abs(scalar)^2
	// for conformity with vectors (for vectors this func is preferred over length to avoid the sqrt)
	inline int length_sqr (int x);
	
	// scalar normalize for conformity with vectors
	// normalize(-6.2f) = -1f, normalize(7) = 1, normalize(0) = <div 0>
	// can be useful in some cases
	inline int normalize (int x);
	
	// normalize(x) for length(x) != 0 else 0
	inline int normalizesafe (int x);
	
	
}


#include "int.inl"
