// file was generated by kissmath.py at <TODO: add github link>
#pragma once

////// Forward declarations

#include "int64.hpp"

namespace kissmath {
	//// forward declarations
	
	struct int64v3;
	struct float4;
	struct int4;
	struct int64v2;
	struct bool4;
	struct uint8v4;
	
	struct int64v4 {
		union { // Union with named members and array members to allow vector[] operator, not 100% sure that this is not undefined behavoir, but I think all compilers definitely don't screw up this use case
			struct {
				int64	x, y, z, w;
			};
			int64		arr[4];
		};
		
		// Component indexing operator
		inline constexpr int64& operator[] (int i);
		
		// Component indexing operator
		inline constexpr int64 const& operator[] (int i) const;
		
		
		// uninitialized constructor
		inline int64v4 () = default;
		
		// sets all components to one value
		// implicit constructor -> float3(x,y,z) * 5 will be turned into float3(x,y,z) * float3(5) by to compiler to be able to execute operator*(float3, float3), which is desirable
		// and short initialization like float3 a = 0; works
		inline constexpr int64v4 (int64 all);
		
		// supply all components
		inline constexpr int64v4 (int64 x, int64 y, int64 z, int64 w);
		
		// extend vector
		inline constexpr int64v4 (int64v2 xy, int64 z, int64 w);
		
		// extend vector
		inline constexpr int64v4 (int64v3 xyz, int64 w);
		
		
		//// Truncating cast operators
		
		// truncating cast operator
		inline constexpr explicit operator int64v2 () const;
		
		// truncating cast operator
		inline constexpr explicit operator int64v3 () const;
		
		
		//// Type cast operators
		
		// type cast operator
		inline constexpr explicit operator bool4 () const;
		
		// type cast operator
		inline constexpr explicit operator float4 () const;
		
		// type cast operator
		inline constexpr explicit operator int4 () const;
		
		// type cast operator
		inline constexpr explicit operator uint8v4 () const;
		
		
		// componentwise arithmetic operator
		inline int64v4 operator+= (int64v4 r);
		
		// componentwise arithmetic operator
		inline int64v4 operator-= (int64v4 r);
		
		// componentwise arithmetic operator
		inline int64v4 operator*= (int64v4 r);
		
		// componentwise arithmetic operator
		inline int64v4 operator/= (int64v4 r);
		
	};
	
	//// arthmethic ops
	
	inline constexpr int64v4 operator+ (int64v4 v);
	
	inline constexpr int64v4 operator- (int64v4 v);
	
	inline constexpr int64v4 operator+ (int64v4 l, int64v4 r);
	
	inline constexpr int64v4 operator- (int64v4 l, int64v4 r);
	
	inline constexpr int64v4 operator* (int64v4 l, int64v4 r);
	
	inline constexpr int64v4 operator/ (int64v4 l, int64v4 r);
	
	
	//// bitwise ops
	
	inline constexpr int64v4 operator~ (int64v4 v);
	
	inline constexpr int64v4 operator& (int64v4 l, int64v4 r);
	
	inline constexpr int64v4 operator| (int64v4 l, int64v4 r);
	
	inline constexpr int64v4 operator^ (int64v4 l, int64v4 r);
	
	inline constexpr int64v4 operator<< (int64v4 l, int64v4 r);
	
	inline constexpr int64v4 operator>> (int64v4 l, int64v4 r);
	
	
	//// comparison ops
	
	// componentwise comparison returns a bool vector
	inline constexpr bool4 operator< (int64v4 l, int64v4 r);
	
	// componentwise comparison returns a bool vector
	inline constexpr bool4 operator<= (int64v4 l, int64v4 r);
	
	// componentwise comparison returns a bool vector
	inline constexpr bool4 operator> (int64v4 l, int64v4 r);
	
	// componentwise comparison returns a bool vector
	inline constexpr bool4 operator>= (int64v4 l, int64v4 r);
	
	// componentwise equality comparison, returns a bool vector
	inline constexpr bool4 equal (int64v4 l, int64v4 r);
	
	// componentwise inequality comparison, returns a bool vector
	inline constexpr bool4 nequal (int64v4 l, int64v4 r);
	
	// full equality comparison, returns true only if all components are equal
	inline constexpr bool operator== (int64v4 l, int64v4 r);
	
	// full inequality comparison, returns true if any components are inequal
	inline constexpr bool operator!= (int64v4 l, int64v4 r);
	
	// componentwise ternary (c ? l : r)
	inline constexpr int64v4 select (bool4 c, int64v4 l, int64v4 r);
	
	
	//// misc ops
	// componentwise absolute
	inline int64v4 abs (int64v4 v);
	
	// componentwise minimum
	inline constexpr int64v4 min (int64v4 l, int64v4 r);
	
	// componentwise maximum
	inline constexpr int64v4 max (int64v4 l, int64v4 r);
	
	// componentwise clamp into range [a,b]
	inline constexpr int64v4 clamp (int64v4 x, int64v4 a, int64v4 b);
	
	// componentwise clamp into range [0,1] also known as saturate in hlsl
	inline constexpr int64v4 clamp (int64v4 x);
	
	// get minimum component of vector, optionally get component index via min_index
	inline int64 min_component (int64v4 v, int* min_index=nullptr);
	
	// get maximum component of vector, optionally get component index via max_index
	inline int64 max_component (int64v4 v, int* max_index=nullptr);
	
	
	// componentwise wrap
	inline int64v4 wrap (int64v4 v, int64v4 range);
	
	// componentwise wrap
	inline int64v4 wrap (int64v4 v, int64v4 a, int64v4 b);
	
	
	
	//// Vector math
	
	// squared magnitude of vector, cheaper than length() because it avoids the sqrt(), some algorithms only need the squared magnitude
	inline constexpr int64 length_sqr (int64v4 v);
	
	// dot product
	inline constexpr int64 dot (int64v4 l, int64v4 r);
	
}


#include "int64v4.inl"
