// file was generated by kissmath.py at <TODO: add github link>

////// Inline definitions

namespace kissmath {
	
	
	inline float2x2 rotate2 (float ang) {
		float s = std::sin(ang), c = std::cos(ang);
		return float2x2(
						 c, -s,
						 s,  c
			   );
	}
	
	inline constexpr float2x2 scale (float2 v) {
		return float2x2(
						v.x,   0,
						  0, v.y
			   );
	}
	
	inline constexpr float2x3 translate (float2 v) {
		return float2x3(
						1, 0, v.x,
						0, 1, v.y
			   );
	}
	
	
}

