// file was generated by kissmath.py at <TODO: add github link>
#pragma once

////// Forward declarations

#include "float2.hpp"
#include "float2x2.hpp"
#include "float2x3.hpp"

namespace kissmath {
	
	inline float2x2 rotate2 (float ang);
	
	inline constexpr float2x2 scale (float2 v);
	
	inline constexpr float2x3 translate (float2 v);
	
	
	
}


#include "transform2d.inl"
