// file was generated by kissmath.py at <TODO: add github link>
#pragma once

#include "float2.hpp"

namespace kissmath {
	
	//// matrix forward declarations
	struct float4x4;
	struct float3x4;
	struct float3x3;
	
	struct float2x2 {
		float2 arr[2]; // column major for compatibility with OpenGL
		
		//// Accessors
		
		// get cell with row, column indecies
		float const& get (int r, int c) const;
		
		// get matrix column
		float2 const& get_column (int indx) const;
		
		// get matrix row
		float2 get_row (int indx) const;
		
		
		//// Constructors
		
		// uninitialized constructor
		float2x2 ();
		
		// supply one value for all cells
		explicit float2x2 (float all);
		
		// supply all cells, in row major order for readability -> c<row><column>
		explicit float2x2 (float c00, float c01,
						   float c10, float c11);
		
		
		// static rows() and columns() methods are preferred over constructors, to avoid confusion if column or row vectors are supplied to the constructor
		// supply all row vectors
		static float2x2 rows (float2 row0, float2 row1);
		
		// supply all cells in row major order
		static float2x2 rows (float c00, float c01,
							  float c10, float c11);
		
		// supply all column vectors
		static float2x2 columns (float2 col0, float2 col1);
		
		// supply all cells in column major order
		static float2x2 columns (float c00, float c10,
								 float c01, float c11);
		
		
		// identity matrix
		static float2x2 identity ();
		
		
		// Casting operators
		
		// extend/truncate matrix of other size
		explicit operator float4x4 () const;
		
		// extend/truncate matrix of other size
		explicit operator float3x4 () const;
		
		// extend/truncate matrix of other size
		explicit operator float3x3 () const;
		
		
		// Componentwise operators; These might be useful in some cases
		
		// add scalar to all matrix cells
		float2x2& operator+= (float r);
		
		// substract scalar from all matrix cells
		float2x2& operator-= (float r);
		
		// multiply scalar with all matrix cells
		float2x2& operator*= (float r);
		
		// divide all matrix cells by scalar
		float2x2& operator/= (float r);
		
		
		// Matrix multiplication
		
		// matrix-matrix muliplication
		float2x2& operator*= (float2x2 const& r);
		
	};
	
	// Componentwise operators; These might be useful in some cases
	
	
	// componentwise matrix_cell + matrix_cell
	float2x2 operator+ (float2x2 const& l, float2x2 const& r);
	
	// componentwise matrix_cell + scalar
	float2x2 operator+ (float2x2 const& l, float r);
	
	// componentwise scalar + matrix_cell
	float2x2 operator+ (float l, float2x2 const& r);
	
	
	// componentwise matrix_cell - matrix_cell
	float2x2 operator- (float2x2 const& l, float2x2 const& r);
	
	// componentwise matrix_cell - scalar
	float2x2 operator- (float2x2 const& l, float r);
	
	// componentwise scalar - matrix_cell
	float2x2 operator- (float l, float2x2 const& r);
	
	
	// componentwise matrix_cell * matrix_cell
	float2x2 mul_componentwise (float2x2 const& l, float2x2 const& r);
	
	// componentwise matrix_cell * scalar
	float2x2 operator* (float2x2 const& l, float r);
	
	// componentwise scalar * matrix_cell
	float2x2 operator* (float l, float2x2 const& r);
	
	
	// componentwise matrix_cell / matrix_cell
	float2x2 div_componentwise (float2x2 const& l, float2x2 const& r);
	
	// componentwise matrix_cell / scalar
	float2x2 operator/ (float2x2 const& l, float r);
	
	// componentwise scalar / matrix_cell
	float2x2 operator/ (float l, float2x2 const& r);
	
	
	// Matrix ops
	
	// matrix-matrix multiply
	float2x2 operator* (float2x2 const& l, float2x2 const& r);
	
	// matrix-vector multiply
	float2 operator* (float2x2 const& l, float2 r);
	
	// vector-matrix multiply
	float2 operator* (float2 l, float2x2 const& r);
	
	float2x2 transpose (float2x2 const& m);
	
	
	float determinant (float2x2 const& mat);
	
	float2x2 inverse (float2x2 const& mat);
	
}

