// file was generated by kissmath.py at <TODO: add github link>
#include "float3.hpp"

#include "bool3.hpp"
#include "uint8v3.hpp"
#include "float4.hpp"
#include "int64v3.hpp"
#include "float2.hpp"
#include "int3.hpp"

namespace kissmath {
	//// forward declarations
	// typedef these because the _t suffix is kinda unwieldy when using these types often
	
	typedef uint8_t uint8;
	typedef int64_t int64;
	
	// Component indexing operator
	float& float3::operator[] (int i) {
		return arr[i];
	}
	
	// Component indexing operator
	float const& float3::operator[] (int i) const {
		return arr[i];
	}
	
	//// sets all components to one value
	//// implicit constructor -> float3(x,y,z) * 5 will be turned into float3(x,y,z) * float3(5) by to compiler to be able to execute operator*(float3, float3), which is desirable
	//// and short initialization like float3 a = 0; works
	//constexpr float3::float3 (float all): x{all}, y{all}, z{all} {
	//	
	//}
	//
	//// supply all components
	//constexpr float3::float3 (float x, float y, float z): x{x}, y{y}, z{z} {
	//	
	//}
	
	// extend vector
	float3::float3 (float2 xy, float z): x{xy.x}, y{xy.y}, z{z} {
		
	}
	
	// truncate vector
	float3::float3 (float4 v): x{v.x}, y{v.y}, z{v.z} {
		
	}
	
	//// Truncating cast operators
	
	
	// truncating cast operator
	float3::operator float2 () const {
		return float2(x, y);
	}
	
	//// Type cast operators
	
	
	// type cast operator
	float3::operator bool3 () const {
		return bool3((bool)x, (bool)y, (bool)z);
	}
	
	// type cast operator
	float3::operator uint8v3 () const {
		return uint8v3((uint8)x, (uint8)y, (uint8)z);
	}
	
	// type cast operator
	float3::operator int64v3 () const {
		return int64v3((int64)x, (int64)y, (int64)z);
	}
	
	// type cast operator
	float3::operator int3 () const {
		return int3((int)x, (int)y, (int)z);
	}
	
	
	// componentwise arithmetic operator
	float3 float3::operator+= (float3 r) {
		x += r.x;
		y += r.y;
		z += r.z;
		return *this;
	}
	
	// componentwise arithmetic operator
	float3 float3::operator-= (float3 r) {
		x -= r.x;
		y -= r.y;
		z -= r.z;
		return *this;
	}
	
	// componentwise arithmetic operator
	float3 float3::operator*= (float3 r) {
		x *= r.x;
		y *= r.y;
		z *= r.z;
		return *this;
	}
	
	// componentwise arithmetic operator
	float3 float3::operator/= (float3 r) {
		x /= r.x;
		y /= r.y;
		z /= r.z;
		return *this;
	}
	
	//// arthmethic ops
	
	
	float3 operator+ (float3 v) {
		return float3(+v.x, +v.y, +v.z);
	}
	
	float3 operator- (float3 v) {
		return float3(-v.x, -v.y, -v.z);
	}
	
	float3 operator+ (float3 l, float3 r) {
		return float3(l.x + r.x, l.y + r.y, l.z + r.z);
	}
	
	float3 operator- (float3 l, float3 r) {
		return float3(l.x - r.x, l.y - r.y, l.z - r.z);
	}
	
	float3 operator* (float3 l, float3 r) {
		return float3(l.x * r.x, l.y * r.y, l.z * r.z);
	}
	
	float3 operator/ (float3 l, float3 r) {
		return float3(l.x / r.x, l.y / r.y, l.z / r.z);
	}
	
	//// bitwise ops
	
	
	//// comparison ops
	
	
	// componentwise comparison returns a bool vector
	bool3 operator< (float3 l, float3 r) {
		return bool3(l.x < r.x, l.y < r.y, l.z < r.z);
	}
	
	// componentwise comparison returns a bool vector
	bool3 operator<= (float3 l, float3 r) {
		return bool3(l.x <= r.x, l.y <= r.y, l.z <= r.z);
	}
	
	// componentwise comparison returns a bool vector
	bool3 operator> (float3 l, float3 r) {
		return bool3(l.x > r.x, l.y > r.y, l.z > r.z);
	}
	
	// componentwise comparison returns a bool vector
	bool3 operator>= (float3 l, float3 r) {
		return bool3(l.x >= r.x, l.y >= r.y, l.z >= r.z);
	}
	
	// componentwise comparison returns a bool vector
	bool3 operator== (float3 l, float3 r) {
		return bool3(l.x == r.x, l.y == r.y, l.z == r.z);
	}
	
	// componentwise comparison returns a bool vector
	bool3 operator!= (float3 l, float3 r) {
		return bool3(l.x != r.x, l.y != r.y, l.z != r.z);
	}
	
	// vectors are equal, equivalent to all(l == r)
	bool equal (float3 l, float3 r) {
		return all(l == r);
	}
	
	// componentwise ternary (c ? l : r)
	float3 select (bool3 c, float3 l, float3 r) {
		return float3(c.x ? l.x : r.x, c.y ? l.y : r.y, c.z ? l.z : r.z);
	}
	
	//// misc ops
	
	// componentwise absolute
	float3 abs (float3 v) {
		return float3(abs(v.x), abs(v.y), abs(v.z));
	}
	
	// componentwise minimum
	float3 min (float3 l, float3 r) {
		return float3(min(l.x,r.x), min(l.y,r.y), min(l.z,r.z));
	}
	
	// componentwise maximum
	float3 max (float3 l, float3 r) {
		return float3(max(l.x,r.x), max(l.y,r.y), max(l.z,r.z));
	}
	
	// componentwise clamp into range [a,b]
	float3 clamp (float3 x, float3 a, float3 b) {
		return min(max(x,a), b);
	}
	
	// componentwise clamp into range [0,1] also known as saturate in hlsl
	float3 clamp (float3 x) {
		return min(max(x, float(0)), float(1));
	}
	
	// get minimum component of vector, optionally get component index via min_index
	float min_component (float3 v, int* min_index) {
		int index = 0;
		float min_val = v.x;	
		for (int i=1; i<3; ++i) {
			if (v.arr[i] <= min_val) {
				index = i;
				min_val = v.arr[i];
			}
		}
		if (min_index) *min_index = index;
		return min_val;
	}
	
	// get maximum component of vector, optionally get component index via max_index
	float max_component (float3 v, int* max_index) {
		int index = 0;
		float max_val = v.x;	
		for (int i=1; i<3; ++i) {
			if (v.arr[i] >= max_val) {
				index = i;
				max_val = v.arr[i];
			}
		}
		if (max_index) *max_index = index;
		return max_val;
	}
	
	
	// componentwise floor
	float3 floor (float3 v) {
		return float3(floor(v.x), floor(v.y), floor(v.z));
	}
	
	// componentwise ceil
	float3 ceil (float3 v) {
		return float3(ceil(v.x), ceil(v.y), ceil(v.z));
	}
	
	// componentwise round
	float3 round (float3 v) {
		return float3(round(v.x), round(v.y), round(v.z));
	}
	
	// componentwise floor to int
	int3 floori (float3 v) {
		return int3(floori(v.x), floori(v.y), floori(v.z));
	}
	
	// componentwise ceil to int
	int3 ceili (float3 v) {
		return int3(ceili(v.x), ceili(v.y), ceili(v.z));
	}
	
	// componentwise round to int
	int3 roundi (float3 v) {
		return int3(roundi(v.x), roundi(v.y), roundi(v.z));
	}
	
	// componentwise pow
	float3 pow (float3 v, float3 e) {
		return float3(pow(v.x,e.x), pow(v.y,e.y), pow(v.z,e.z));
	}
	
	// componentwise wrap
	float3 wrap (float3 v, float3 range) {
		return float3(wrap(v.x,range.x), wrap(v.y,range.y), wrap(v.z,range.z));
	}
	
	// componentwise wrap
	float3 wrap (float3 v, float3 a, float3 b) {
		return float3(wrap(v.x,a.x,b.x), wrap(v.y,a.y,b.y), wrap(v.z,a.z,b.z));
	}
	
	
	//// Angle conversion
	
	
	// converts degrees to radiants
	float3 to_radians (float3 deg) {
		return deg * DEG_TO_RAD;
	}
	
	// converts radiants to degrees
	float3 to_degrees (float3 rad) {
		return rad * RAD_TO_DEG;
	}
	
	// converts degrees to radiants
	// shortform to make degree literals more readable
	float3 deg (float3 deg) {
		return deg * DEG_TO_RAD;
	}
	
	// linear interpolation
	// like getting the output of a linear function
	// ex. t=0 -> a ; t=1 -> b ; t=0.5 -> (a+b)/2
	float3 lerp (float3 a, float3 b, float3 t) {
		return t * (b - a) + a;
	}
	
	// linear mapping
	// sometimes called inverse linear interpolation
	// like getting the x for a y on a linear function
	// ex. map(70, 0,100) -> 0.7 ; map(0.5, -1,+1) -> 0.75
	float3 map (float3 x, float3 in_a, float3 in_b) {
		return (x - in_a) / (in_b - in_a);
	}
	
	// linear remapping
	// equivalent of lerp(out_a, out_b, map(x, in_a, in_b))
	float3 map (float3 x, float3 in_a, float3 in_b, float3 out_a, float3 out_b) {
		return lerp(out_a, out_b, map(x, in_a, in_b));
	}
	
	//// Various interpolation
	
	
	// standard smoothstep interpolation
	float3 smoothstep (float3 x) {
		float3 t = clamp(x);
		return t * t * (3.0f - 2.0f * t);
	}
	
	// 3 point bezier interpolation
	float3 bezier (float3 a, float3 b, float3 c, float t) {
		float3 d = lerp(a, b, t);
		float3 e = lerp(b, c, t);
		float3 f = lerp(d, e, t);
		return f;
	}
	
	// 4 point bezier interpolation
	float3 bezier (float3 a, float3 b, float3 c, float3 d, float t) {
		return bezier(
					  lerp(a, b, t),
					  lerp(b, c, t),
					  lerp(c, d, t),
					  t
			   );
	}
	
	// 5 point bezier interpolation
	float3 bezier (float3 a, float3 b, float3 c, float3 d, float3 e, float t) {
		return bezier(
					  lerp(a, b, t),
					  lerp(b, c, t),
					  lerp(c, d, t),
					  lerp(d, e, t),
					  t
			   );
	}
	
	//// Vector math
	
	
	// magnitude of vector
	float length (float3 v) {
		return sqrt((float)(v.x * v.x + v.y * v.y + v.z * v.z));
	}
	
	// squared magnitude of vector, cheaper than length() because it avoids the sqrt(), some algorithms only need the squared magnitude
	float length_sqr (float3 v) {
		return v.x * v.x + v.y * v.y + v.z * v.z;
	}
	
	// distance between points, equivalent to length(a - b)
	float distance (float3 a, float3 b) {
		return length(a - b);
	}
	
	// normalize vector so that it has length() = 1, undefined for zero vector
	float3 normalize (float3 v) {
		return float3(v) / length(v);
	}
	
	// normalize vector so that it has length() = 1, returns zero vector if vector was zero vector
	float3 normalizesafe (float3 v) {
		float len = length(v);
		if (len == float(0)) {
			return float(0);
		}
		return float3(v) / float3(len);
	}
	
	// dot product
	float dot (float3 l, float3 r) {
		return l.x * r.x + l.y * r.y + l.z * r.z;
	}
	
	// 3d cross product
	float3 cross (float3 l, float3 r) {
		return float3(
					  l.y * r.z - l.z * r.y,
					  l.z * r.x - l.x * r.z,
					  l.x * r.y - l.y * r.x);
	}
}

