// file was generated by kissmath.py at <TODO: add github link>
#pragma once

#include "float4.hpp"

namespace kissmath {
	
	//// matrix forward declarations
	struct float3x4;
	struct float2x2;
	struct float3x3;
	
	struct float4x4 {
		float4 arr[4]; // column major for compatibility with OpenGL
		
		//// Accessors
		
		// get cell with row, column indecies
		float const& get (int r, int c) const;
		
		// get matrix column
		float4 const& get_column (int indx) const;
		
		// get matrix row
		float4 get_row (int indx) const;
		
		
		//// Constructors
		
		// uninitialized constructor
		float4x4 ();
		
		// supply one value for all cells
		explicit float4x4 (float all);
		
		// supply all cells, in row major order for readability -> c<row><column>
		constexpr explicit float4x4 (float c00, float c01, float c02, float c03,
						   float c10, float c11, float c12, float c13,
						   float c20, float c21, float c22, float c23,
						   float c30, float c31, float c32, float c33): 
			arr{float4(c00, c10, c20, c30),
				float4(c01, c11, c21, c31),
				float4(c02, c12, c22, c32),
				float4(c03, c13, c23, c33)} {
			
		}
		
		
		// static rows() and columns() methods are preferred over constructors, to avoid confusion if column or row vectors are supplied to the constructor
		// supply all row vectors
		static float4x4 rows (float4 row0, float4 row1, float4 row2, float4 row3);
		
		// supply all cells in row major order
		static float4x4 rows (float c00, float c01, float c02, float c03,
							  float c10, float c11, float c12, float c13,
							  float c20, float c21, float c22, float c23,
							  float c30, float c31, float c32, float c33);
		
		// supply all column vectors
		static float4x4 columns (float4 col0, float4 col1, float4 col2, float4 col3);
		
		// supply all cells in column major order
		static float4x4 columns (float c00, float c10, float c20, float c30,
								 float c01, float c11, float c21, float c31,
								 float c02, float c12, float c22, float c32,
								 float c03, float c13, float c23, float c33);
		
		
		// identity matrix
		static float4x4 identity ();
		
		
		// Casting operators
		
		// extend/truncate matrix of other size
		explicit operator float3x4 () const;
		
		// extend/truncate matrix of other size
		explicit operator float2x2 () const;
		
		// extend/truncate matrix of other size
		explicit operator float3x3 () const;
		
		
		// Componentwise operators; These might be useful in some cases
		
		// add scalar to all matrix cells
		float4x4& operator+= (float r);
		
		// substract scalar from all matrix cells
		float4x4& operator-= (float r);
		
		// multiply scalar with all matrix cells
		float4x4& operator*= (float r);
		
		// divide all matrix cells by scalar
		float4x4& operator/= (float r);
		
		
		// Matrix multiplication
		
		// matrix-matrix muliplication
		float4x4& operator*= (float4x4 const& r);
		
	};
	
	// Componentwise operators; These might be useful in some cases
	
	
	// componentwise matrix_cell + matrix_cell
	float4x4 operator+ (float4x4 const& l, float4x4 const& r);
	
	// componentwise matrix_cell + scalar
	float4x4 operator+ (float4x4 const& l, float r);
	
	// componentwise scalar + matrix_cell
	float4x4 operator+ (float l, float4x4 const& r);
	
	
	// componentwise matrix_cell - matrix_cell
	float4x4 operator- (float4x4 const& l, float4x4 const& r);
	
	// componentwise matrix_cell - scalar
	float4x4 operator- (float4x4 const& l, float r);
	
	// componentwise scalar - matrix_cell
	float4x4 operator- (float l, float4x4 const& r);
	
	
	// componentwise matrix_cell * matrix_cell
	float4x4 mul_componentwise (float4x4 const& l, float4x4 const& r);
	
	// componentwise matrix_cell * scalar
	float4x4 operator* (float4x4 const& l, float r);
	
	// componentwise scalar * matrix_cell
	float4x4 operator* (float l, float4x4 const& r);
	
	
	// componentwise matrix_cell / matrix_cell
	float4x4 div_componentwise (float4x4 const& l, float4x4 const& r);
	
	// componentwise matrix_cell / scalar
	float4x4 operator/ (float4x4 const& l, float r);
	
	// componentwise scalar / matrix_cell
	float4x4 operator/ (float l, float4x4 const& r);
	
	
	// Matrix ops
	
	// matrix-matrix multiply
	float4x4 operator* (float4x4 const& l, float4x4 const& r);
	
	// matrix-vector multiply
	float4 operator* (float4x4 const& l, float4 r);
	
	// vector-matrix multiply
	float4 operator* (float4 l, float4x4 const& r);
	
	float4x4 transpose (float4x4 const& m);
	
	
	float determinant (float4x4 const& mat);
	
	float4x4 inverse (float4x4 const& mat);
	
}

