// file was generated by kissmath.py at <TODO: add github link>
#pragma once

////// Forward declarations

#include "float3.hpp"
#include "float2.hpp"

namespace kissmath {
	
	//// matrix forward declarations
	struct float2x2;
	struct float3x3;
	struct float4x4;
	struct float3x4;
	
	struct float2x3 {
		float2 arr[3]; // column major for compatibility with OpenGL
		
		//// Accessors
		
		// get cell with row, column indecies
		inline constexpr float const& get (int r, int c) const;
		
		// get matrix column
		inline constexpr float2 const& get_column (int indx) const;
		
		// get matrix row
		inline constexpr float3 get_row (int indx) const;
		
		
		//// Constructors
		
		// uninitialized constructor
		inline float2x3 ();
		
		// supply one value for all cells
		inline constexpr explicit float2x3 (float all);
		
		// supply all cells, in row major order for readability -> c<row><column>
		inline constexpr explicit float2x3 (float c00, float c01, float c02,
											float c10, float c11, float c12);
		
		
		// static rows() and columns() methods are preferred over constructors, to avoid confusion if column or row vectors are supplied to the constructor
		// supply all row vectors
		static inline constexpr float2x3 rows (float3 row0, float3 row1);
		
		// supply all cells in row major order
		static inline constexpr float2x3 rows (float c00, float c01, float c02,
											   float c10, float c11, float c12);
		
		// supply all column vectors
		static inline constexpr float2x3 columns (float2 col0, float2 col1, float2 col2);
		
		// supply all cells in column major order
		static inline constexpr float2x3 columns (float c00, float c10,
												  float c01, float c11,
												  float c02, float c12);
		
		
		// identity matrix
		static inline constexpr float2x3 identity ();
		
		
		// Casting operators
		
		// extend/truncate matrix of other size
		inline constexpr explicit operator float2x2 () const;
		
		// extend/truncate matrix of other size
		inline constexpr explicit operator float3x3 () const;
		
		// extend/truncate matrix of other size
		inline constexpr explicit operator float4x4 () const;
		
		// extend/truncate matrix of other size
		inline constexpr explicit operator float3x4 () const;
		
		
		// Componentwise operators; These might be useful in some cases
		
		// add scalar to all matrix cells
		inline float2x3& operator+= (float r);
		
		// substract scalar from all matrix cells
		inline float2x3& operator-= (float r);
		
		// multiply scalar with all matrix cells
		inline float2x3& operator*= (float r);
		
		// divide all matrix cells by scalar
		inline float2x3& operator/= (float r);
		
		
		// Matrix multiplication
		
		// matrix-matrix muliplication
		inline float2x3& operator*= (float2x3 const& r);
		
	};
	
	// Componentwise operators; These might be useful in some cases
	
	
	// componentwise matrix_cell + matrix_cell
	inline constexpr float2x3 operator+ (float2x3 const& l, float2x3 const& r);
	
	// componentwise matrix_cell + scalar
	inline constexpr float2x3 operator+ (float2x3 const& l, float r);
	
	// componentwise scalar + matrix_cell
	inline constexpr float2x3 operator+ (float l, float2x3 const& r);
	
	
	// componentwise matrix_cell - matrix_cell
	inline constexpr float2x3 operator- (float2x3 const& l, float2x3 const& r);
	
	// componentwise matrix_cell - scalar
	inline constexpr float2x3 operator- (float2x3 const& l, float r);
	
	// componentwise scalar - matrix_cell
	inline constexpr float2x3 operator- (float l, float2x3 const& r);
	
	
	// componentwise matrix_cell * matrix_cell
	inline constexpr float2x3 mul_componentwise (float2x3 const& l, float2x3 const& r);
	
	// componentwise matrix_cell * scalar
	inline constexpr float2x3 operator* (float2x3 const& l, float r);
	
	// componentwise scalar * matrix_cell
	inline constexpr float2x3 operator* (float l, float2x3 const& r);
	
	
	// componentwise matrix_cell / matrix_cell
	inline constexpr float2x3 div_componentwise (float2x3 const& l, float2x3 const& r);
	
	// componentwise matrix_cell / scalar
	inline constexpr float2x3 operator/ (float2x3 const& l, float r);
	
	// componentwise scalar / matrix_cell
	inline constexpr float2x3 operator/ (float l, float2x3 const& r);
	
	
	// Matrix ops
	
	// matrix-matrix multiply
	inline float2x3 operator* (float2x2 const& l, float2x3 const& r);
	
	// matrix-matrix multiply
	inline float2x3 operator* (float2x3 const& l, float3x3 const& r);
	
	// matrix-vector multiply
	inline float2 operator* (float2x3 const& l, float3 r);
	
	// vector-matrix multiply
	inline float3 operator* (float2 l, float2x3 const& r);
	
	
	// Matrix operation shortforms so that you can treat a 2x3 matrix as a 2x2 matrix plus translation
	
	// shortform for float2x3 * (float3x3)float2x2
	inline float2x3 operator* (float2x3 const& l, float2x2 const& r);
	
	// shortform for float2x3 * (float3x3)float2x3
	inline float2x3 operator* (float2x3 const& l, float2x3 const& r);
	
	// shortform for float2x3 * float3(float2, 1)
	inline float2 operator* (float2x3 const& l, float2 r);
	
}


#include "float2x3.inl"
