// file was generated by kissmath.py at <TODO: add github link>
#pragma once

#include "int.hpp"

namespace kissmath {
	//// forward declarations
	
	struct uint8v2;
	struct int64v2;
	struct int4;
	struct bool2;
	struct float2;
	struct int3;
	
	struct int2 {
		union { // Union with named members and array members to allow vector[] operator, not 100% sure that this is not undefined behavoir, but I think all compilers definitely don't screw up this use case
			struct {
				int	x, y;
			};
			int		arr[2];
		};
		
		// Component indexing operator
		int& operator[] (int i);
		
		// Component indexing operator
		int const& operator[] (int i) const;
		
		
		// uninitialized constructor
		int2 ();
		
		// sets all components to one value
		// implicit constructor -> float3(x,y,z) * 5 will be turned into float3(x,y,z) * float3(5) by to compiler to be able to execute operator*(float3, float3), which is desirable
		// and short initialization like float3 a = 0; works
		int2 (int all);
		
		// supply all components
		int2 (int x, int y);
		
		// truncate vector
		int2 (int3 v);
		
		// truncate vector
		int2 (int4 v);
		
		//// Truncating cast operators
		
		
		//// Type cast operators
		
		// type cast operator
		explicit operator int64v2 () const;
		
		// type cast operator
		explicit operator float2 () const;
		
		// type cast operator
		explicit operator uint8v2 () const;
		
		// type cast operator
		explicit operator bool2 () const;
		
		
		// componentwise arithmetic operator
		int2 operator+= (int2 r);
		
		// componentwise arithmetic operator
		int2 operator-= (int2 r);
		
		// componentwise arithmetic operator
		int2 operator*= (int2 r);
		
		// componentwise arithmetic operator
		int2 operator/= (int2 r);
		
	};
	
	//// arthmethic ops
	
	int2 operator+ (int2 v);
	
	int2 operator- (int2 v);
	
	int2 operator+ (int2 l, int2 r);
	
	int2 operator- (int2 l, int2 r);
	
	int2 operator* (int2 l, int2 r);
	
	int2 operator/ (int2 l, int2 r);
	
	
	//// bitwise ops
	
	int2 operator~ (int2 v);
	
	int2 operator& (int2 l, int2 r);
	
	int2 operator| (int2 l, int2 r);
	
	int2 operator^ (int2 l, int2 r);
	
	
	//// comparison ops
	
	// componentwise comparison returns a bool vector
	bool2 operator< (int2 l, int2 r);
	
	// componentwise comparison returns a bool vector
	bool2 operator<= (int2 l, int2 r);
	
	// componentwise comparison returns a bool vector
	bool2 operator> (int2 l, int2 r);
	
	// componentwise comparison returns a bool vector
	bool2 operator>= (int2 l, int2 r);
	
	// componentwise comparison returns a bool vector
	bool2 operator== (int2 l, int2 r);
	
	// componentwise comparison returns a bool vector
	bool2 operator!= (int2 l, int2 r);
	
	// vectors are equal, equivalent to all(l == r)
	bool equal (int2 l, int2 r);
	
	// componentwise ternary (c ? l : r)
	int2 select (bool2 c, int2 l, int2 r);
	
	
	//// misc ops
	// componentwise absolute
	int2 abs (int2 v);
	
	// componentwise minimum
	int2 min (int2 l, int2 r);
	
	// componentwise maximum
	int2 max (int2 l, int2 r);
	
	// componentwise clamp into range [a,b]
	int2 clamp (int2 x, int2 a, int2 b);
	
	// componentwise clamp into range [0,1] also known as saturate in hlsl
	int2 clamp (int2 x);
	
	// get minimum component of vector, optionally get component index via min_index
	int min_component (int2 v, int* min_index=nullptr);
	
	// get maximum component of vector, optionally get component index via max_index
	int max_component (int2 v, int* max_index=nullptr);
	
	
	// componentwise wrap
	int2 wrap (int2 v, int2 range);
	
	// componentwise wrap
	int2 wrap (int2 v, int2 a, int2 b);
	
	
	
	//// Vector math
	
	// magnitude of vector
	float length (int2 v);
	
	// squared magnitude of vector, cheaper than length() because it avoids the sqrt(), some algorithms only need the squared magnitude
	int length_sqr (int2 v);
	
	// distance between points, equivalent to length(a - b)
	float distance (int2 a, int2 b);
	
	// normalize vector so that it has length() = 1, undefined for zero vector
	float2 normalize (int2 v);
	
	// normalize vector so that it has length() = 1, returns zero vector if vector was zero vector
	float2 normalizesafe (int2 v);
	
	// dot product
	int dot (int2 l, int2 r);
	
	// 2d cross product hack for convenient 2d stuff
	// same as cross({T.name[:-2]}3(l, 0), {T.name[:-2]}3(r, 0)).z,
	// ie. the cross product of the 2d vectors on the z=0 plane in 3d space and then return the z coord of that (signed mag of cross product)
	int cross (int2 l, int2 r);
	
	// rotate 2d vector counterclockwise 90 deg, ie. int2(-y, x) which is fast
	int2 rotate90 (int2 v);
	
}

