// file was generated by kissmath.py at <TODO: add github link>
#pragma once

#include "int64.hpp"

namespace kissmath {
	//// forward declarations
	
	struct uint8v2;
	struct int64v4;
	struct int64v3;
	struct bool2;
	struct float2;
	struct int2;
	
	struct int64v2 {
		union { // Union with named members and array members to allow vector[] operator, not 100% sure that this is not undefined behavoir, but I think all compilers definitely don't screw up this use case
			struct {
				int64	x, y;
			};
			int64		arr[2];
		};
		
		// Component indexing operator
		int64& operator[] (int i);
		
		// Component indexing operator
		int64 const& operator[] (int i) const;
		
		
		// uninitialized constructor
		int64v2 ();
		
		// sets all components to one value
		// implicit constructor -> float3(x,y,z) * 5 will be turned into float3(x,y,z) * float3(5) by to compiler to be able to execute operator*(float3, float3), which is desirable
		// and short initialization like float3 a = 0; works
		int64v2 (int64 all);
		
		// supply all components
		int64v2 (int64 x, int64 y);
		
		// truncate vector
		int64v2 (int64v3 v);
		
		// truncate vector
		int64v2 (int64v4 v);
		
		
		//// Truncating cast operators
		
		
		//// Type cast operators
		
		// type cast operator
		explicit operator int2 () const;
		
		// type cast operator
		explicit operator float2 () const;
		
		// type cast operator
		explicit operator uint8v2 () const;
		
		// type cast operator
		explicit operator bool2 () const;
		
		
		// componentwise arithmetic operator
		int64v2 operator+= (int64v2 r);
		
		// componentwise arithmetic operator
		int64v2 operator-= (int64v2 r);
		
		// componentwise arithmetic operator
		int64v2 operator*= (int64v2 r);
		
		// componentwise arithmetic operator
		int64v2 operator/= (int64v2 r);
		
	};
	
	//// arthmethic ops
	
	int64v2 operator+ (int64v2 v);
	
	int64v2 operator- (int64v2 v);
	
	int64v2 operator+ (int64v2 l, int64v2 r);
	
	int64v2 operator- (int64v2 l, int64v2 r);
	
	int64v2 operator* (int64v2 l, int64v2 r);
	
	int64v2 operator/ (int64v2 l, int64v2 r);
	
	
	//// bitwise ops
	
	int64v2 operator~ (int64v2 v);
	
	int64v2 operator& (int64v2 l, int64v2 r);
	
	int64v2 operator| (int64v2 l, int64v2 r);
	
	int64v2 operator^ (int64v2 l, int64v2 r);
	
	
	//// comparison ops
	
	// componentwise comparison returns a bool vector
	bool2 operator< (int64v2 l, int64v2 r);
	
	// componentwise comparison returns a bool vector
	bool2 operator<= (int64v2 l, int64v2 r);
	
	// componentwise comparison returns a bool vector
	bool2 operator> (int64v2 l, int64v2 r);
	
	// componentwise comparison returns a bool vector
	bool2 operator>= (int64v2 l, int64v2 r);
	
	// componentwise comparison returns a bool vector
	bool2 operator== (int64v2 l, int64v2 r);
	
	// componentwise comparison returns a bool vector
	bool2 operator!= (int64v2 l, int64v2 r);
	
	// vectors are equal, equivalent to all(l == r)
	bool equal (int64v2 l, int64v2 r);
	
	// componentwise ternary (c ? l : r)
	int64v2 select (bool2 c, int64v2 l, int64v2 r);
	
	
	//// misc ops
	// componentwise absolute
	int64v2 abs (int64v2 v);
	
	// componentwise minimum
	int64v2 min (int64v2 l, int64v2 r);
	
	// componentwise maximum
	int64v2 max (int64v2 l, int64v2 r);
	
	// componentwise clamp into range [a,b]
	int64v2 clamp (int64v2 x, int64v2 a, int64v2 b);
	
	// componentwise clamp into range [0,1] also known as saturate in hlsl
	int64v2 clamp (int64v2 x);
	
	// get minimum component of vector, optionally get component index via min_index
	int64 min_component (int64v2 v, int* min_index=nullptr);
	
	// get maximum component of vector, optionally get component index via max_index
	int64 max_component (int64v2 v, int* max_index=nullptr);
	
	
	// componentwise wrap
	int64v2 wrap (int64v2 v, int64v2 range);
	
	// componentwise wrap
	int64v2 wrap (int64v2 v, int64v2 a, int64v2 b);
	
	
	
	//// Vector math
	
	// squared magnitude of vector, cheaper than length() because it avoids the sqrt(), some algorithms only need the squared magnitude
	int64 length_sqr (int64v2 v);
	
	// dot product
	int64 dot (int64v2 l, int64v2 r);
	
	// 2d cross product hack for convenient 2d stuff
	// same as cross({T.name[:-2]}3(l, 0), {T.name[:-2]}3(r, 0)).z,
	// ie. the cross product of the 2d vectors on the z=0 plane in 3d space and then return the z coord of that (signed mag of cross product)
	int64 cross (int64v2 l, int64v2 r);
	
	// rotate 2d vector counterclockwise 90 deg, ie. int64v2(-y, x) which is fast
	int64v2 rotate90 (int64v2 v);
	
}

