// file was generated by kissmath.py at <TODO: add github link>
#include "int64v2.hpp"

#include "uint8v2.hpp"
#include "int64v4.hpp"
#include "int64v3.hpp"
#include "bool2.hpp"
#include "float2.hpp"
#include "int2.hpp"

namespace kissmath {
	//// forward declarations
	// typedef these because the _t suffix is kinda unwieldy when using these types often
	
	typedef uint8_t uint8;
	typedef int64_t int64;
	typedef int64_t int64;
	
	// Component indexing operator
	int64& int64v2::operator[] (int i) {
		return arr[i];
	}
	
	// Component indexing operator
	int64 const& int64v2::operator[] (int i) const {
		return arr[i];
	}
	
	
	// uninitialized constructor
	int64v2::int64v2 () {
		
	}
	
	// sets all components to one value
	// implicit constructor -> float3(x,y,z) * 5 will be turned into float3(x,y,z) * float3(5) by to compiler to be able to execute operator*(float3, float3), which is desirable
	// and short initialization like float3 a = 0; works
	int64v2::int64v2 (int64 all): x{all}, y{all} {
		
	}
	
	// supply all components
	int64v2::int64v2 (int64 x, int64 y): x{x}, y{y} {
		
	}
	
	// truncate vector
	int64v2::int64v2 (int64v3 v): x{v.x}, y{v.y} {
		
	}
	
	// truncate vector
	int64v2::int64v2 (int64v4 v): x{v.x}, y{v.y} {
		
	}
	
	//// Truncating cast operators
	
	
	//// Type cast operators
	
	
	// type cast operator
	int64v2::operator int2 () const {
		return int2((int)x, (int)y);
	}
	
	// type cast operator
	int64v2::operator float2 () const {
		return float2((float)x, (float)y);
	}
	
	// type cast operator
	int64v2::operator uint8v2 () const {
		return uint8v2((uint8)x, (uint8)y);
	}
	
	// type cast operator
	int64v2::operator bool2 () const {
		return bool2((bool)x, (bool)y);
	}
	
	
	// componentwise arithmetic operator
	int64v2 int64v2::operator+= (int64v2 r) {
		x += r.x;
		y += r.y;
		return *this;
	}
	
	// componentwise arithmetic operator
	int64v2 int64v2::operator-= (int64v2 r) {
		x -= r.x;
		y -= r.y;
		return *this;
	}
	
	// componentwise arithmetic operator
	int64v2 int64v2::operator*= (int64v2 r) {
		x *= r.x;
		y *= r.y;
		return *this;
	}
	
	// componentwise arithmetic operator
	int64v2 int64v2::operator/= (int64v2 r) {
		x /= r.x;
		y /= r.y;
		return *this;
	}
	
	//// arthmethic ops
	
	
	int64v2 operator+ (int64v2 v) {
		return int64v2(+v.x, +v.y);
	}
	
	int64v2 operator- (int64v2 v) {
		return int64v2(-v.x, -v.y);
	}
	
	int64v2 operator+ (int64v2 l, int64v2 r) {
		return int64v2(l.x + r.x, l.y + r.y);
	}
	
	int64v2 operator- (int64v2 l, int64v2 r) {
		return int64v2(l.x - r.x, l.y - r.y);
	}
	
	int64v2 operator* (int64v2 l, int64v2 r) {
		return int64v2(l.x * r.x, l.y * r.y);
	}
	
	int64v2 operator/ (int64v2 l, int64v2 r) {
		return int64v2(l.x / r.x, l.y / r.y);
	}
	
	//// bitwise ops
	
	
	int64v2 operator~ (int64v2 v) {
		return int64v2(~v.x, ~v.y);
	}
	
	int64v2 operator& (int64v2 l, int64v2 r) {
		return int64v2(l.x & r.x, l.y & r.y);
	}
	
	int64v2 operator| (int64v2 l, int64v2 r) {
		return int64v2(l.x | r.x, l.y | r.y);
	}
	
	int64v2 operator^ (int64v2 l, int64v2 r) {
		return int64v2(l.x ^ r.x, l.y ^ r.y);
	}
	
	//// comparison ops
	
	
	// componentwise comparison returns a bool vector
	bool2 operator< (int64v2 l, int64v2 r) {
		return bool2(l.x < r.x, l.y < r.y);
	}
	
	// componentwise comparison returns a bool vector
	bool2 operator<= (int64v2 l, int64v2 r) {
		return bool2(l.x <= r.x, l.y <= r.y);
	}
	
	// componentwise comparison returns a bool vector
	bool2 operator> (int64v2 l, int64v2 r) {
		return bool2(l.x > r.x, l.y > r.y);
	}
	
	// componentwise comparison returns a bool vector
	bool2 operator>= (int64v2 l, int64v2 r) {
		return bool2(l.x >= r.x, l.y >= r.y);
	}
	
	// componentwise comparison returns a bool vector
	bool2 operator== (int64v2 l, int64v2 r) {
		return bool2(l.x == r.x, l.y == r.y);
	}
	
	// componentwise comparison returns a bool vector
	bool2 operator!= (int64v2 l, int64v2 r) {
		return bool2(l.x != r.x, l.y != r.y);
	}
	
	// vectors are equal, equivalent to all(l == r)
	bool equal (int64v2 l, int64v2 r) {
		return all(l == r);
	}
	
	// componentwise ternary (c ? l : r)
	int64v2 select (bool2 c, int64v2 l, int64v2 r) {
		return int64v2(c.x ? l.x : r.x, c.y ? l.y : r.y);
	}
	
	//// misc ops
	
	// componentwise absolute
	int64v2 abs (int64v2 v) {
		return int64v2(abs(v.x), abs(v.y));
	}
	
	// componentwise minimum
	int64v2 min (int64v2 l, int64v2 r) {
		return int64v2(min(l.x,r.x), min(l.y,r.y));
	}
	
	// componentwise maximum
	int64v2 max (int64v2 l, int64v2 r) {
		return int64v2(max(l.x,r.x), max(l.y,r.y));
	}
	
	// componentwise clamp into range [a,b]
	int64v2 clamp (int64v2 x, int64v2 a, int64v2 b) {
		return min(max(x,a), b);
	}
	
	// componentwise clamp into range [0,1] also known as saturate in hlsl
	int64v2 clamp (int64v2 x) {
		return min(max(x, int64(0)), int64(1));
	}
	
	// get minimum component of vector, optionally get component index via min_index
	int64 min_component (int64v2 v, int* min_index) {
		int index = 0;
		int64 min_val = v.x;	
		for (int i=1; i<2; ++i) {
			if (v.arr[i] <= min_val) {
				index = i;
				min_val = v.arr[i];
			}
		}
		if (min_index) *min_index = index;
		return min_val;
	}
	
	// get maximum component of vector, optionally get component index via max_index
	int64 max_component (int64v2 v, int* max_index) {
		int index = 0;
		int64 max_val = v.x;	
		for (int i=1; i<2; ++i) {
			if (v.arr[i] >= max_val) {
				index = i;
				max_val = v.arr[i];
			}
		}
		if (max_index) *max_index = index;
		return max_val;
	}
	
	
	// componentwise wrap
	int64v2 wrap (int64v2 v, int64v2 range) {
		return int64v2(wrap(v.x,range.x), wrap(v.y,range.y));
	}
	
	// componentwise wrap
	int64v2 wrap (int64v2 v, int64v2 a, int64v2 b) {
		return int64v2(wrap(v.x,a.x,b.x), wrap(v.y,a.y,b.y));
	}
	
	
	//// Vector math
	
	
	// squared magnitude of vector, cheaper than length() because it avoids the sqrt(), some algorithms only need the squared magnitude
	int64 length_sqr (int64v2 v) {
		return v.x * v.x + v.y * v.y;
	}
	
	// dot product
	int64 dot (int64v2 l, int64v2 r) {
		return l.x * r.x + l.y * r.y;
	}
	
	// 2d cross product hack for convenient 2d stuff
	// same as cross({T.name[:-2]}3(l, 0), {T.name[:-2]}3(r, 0)).z,
	// ie. the cross product of the 2d vectors on the z=0 plane in 3d space and then return the z coord of that (signed mag of cross product)
	int64 cross (int64v2 l, int64v2 r) {
		return l.x * r.y - l.y * r.x;
	}
	
	// rotate 2d vector counterclockwise 90 deg, ie. int64v2(-y, x) which is fast
	int64v2 rotate90 (int64v2 v) {
		return int64v2(-v.y, v.x);
	}
}

