// file was generated by kissmath.py at <TODO: add github link>
#include "int64.hpp"

namespace kissmath {
	
	// wrap x into range [0,range)
	// negative x wrap back to +range unlike c++ % operator
	// negative range supported
	int64 wrap (int64 x, int64 range) {
		int64 modded = x % range;
		if (range > 0) {
			if (modded < 0) modded += range;
		} else {
			if (modded > 0) modded += range;
		}
		return modded;
	}
	
	// wrap x into [a,b) range
	int64 wrap (int64 x, int64 a, int64 b) {
		x -= a;
		int64 range = b -a;
		
		int64 modulo = wrap(x, range);
		
		return modulo + a;
	}
	
	// clamp x into range [a, b]
	// equivalent to min(max(x,a), b)
	int64 clamp (int64 x, int64 a, int64 b) {
		return min(max(x, a), b);
	}
	
	// clamp x into range [0, 1]
	// also known as saturate in hlsl
	int64 clamp (int64 x) {
		return min(max(x, int64(0)), int64(1));
	}
	
	// returns the greater value of a and b
	int64 min (int64 l, int64 r) {
		return l <= r ? l : r;
	}
	
	// returns the smaller value of a and b
	int64 max (int64 l, int64 r) {
		return l >= r ? l : r;
	}
	
	// equivalent to ternary c ? l : r
	// for conformity with vectors
	int64 select (bool c, int64 l, int64 r) {
		return c ? l : r;
	}
	
	
	// length(scalar) = abs(scalar)
	// for conformity with vectors
	int64 length (int64 x) {
		return std::abs(x);
	}
	
	// length_sqr(scalar) = abs(scalar)^2
	// for conformity with vectors (for vectors this func is preferred over length to avoid the sqrt)
	int64 length_sqr (int64 x) {
		x = std::abs(x);
		return x*x;
	}
	
	// scalar normalize for conformity with vectors
	// normalize(-6.2f) = -1f, normalize(7) = 1, normalize(0) = <div 0>
	// can be useful in some cases
	int64 normalize (int64 x) {
		return x / length(x);
	}
	
	// normalize(x) for length(x) != 0 else 0
	int64 normalizesafe (int64 x) {
		int64 len = length(x);
		if (len == int64(0)) {
			return int64(0);
		}
		return x /= len;
	}
	
}

