// file was generated by kissmath.py at <TODO: add github link>
#pragma once

#include "float2.hpp"
#include "float2x2.hpp"
namespace kissmath {
	
	float2x2 rotate2 (float ang);
	
	float2x2 scale (float2 v);
	
	
	
}

