// file was generated by kissmath.py at <TODO: add github link>
#pragma once

#include "float3.hpp"
#include "float3x3.hpp"
#include "float3x4.hpp"

namespace kissmath {
	
	float3x3 rotate3_X (float ang);
	
	float3x3 rotate3_Y (float ang);
	
	float3x3 rotate3_Z (float ang);
	
	float3x3 scale (float3 v);
	
	float3x4 translate (float3 v);
	
	
	
}

